name: Sample Doppler Secrets Access
on: [workflow_dispatch]

jobs:
    main:
        runs-on: ubuntu-latest # ubuntu, macos, and windows are supported
        steps:
            - name: Install Doppler CLI
              uses: dopplerhq/cli-action@v1

            - name: Test Doppler Access
              run: doppler run -- printenv | grep DOPPLER
              env:
                  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
